[package]
name = "solana_libra_logger"
version = "0.0.0-sol15"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra logger"
license = "Apache-2.0"
edition = "2018"

[dependencies]
backtrace = { version = "0.3.33", features = ["serialize-serde"] }
chrono = "0.4.7"
crossbeam = "^0.4.1"
futures = "0.1.28"
hyper = "0.12.33"
itertools = "0.8.0"
lazy_static = "1.3.0"
mime = "0.3.2"
rand = "0.6.5"
serde = { version = "1.0.96", features = ["derive"] }
serde_json = "1.0.40"
# use this line to change verbosity
slog = { version = "2.5.0", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-envlogger = "2.1.0"
slog-scope = "4.0"
slog-term = "2.4.1"
thread-id = "3.3.0"
tokio = "0.1.22"

# Do NOT add any other inter-project dependencies.
# This is to avoid ever having a circular dependency with the logger crate.
failure = { path = "../failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol15" }

[dev-dependencies]
rand = "0.6.5"
regex = "1.1.9"
