[package]
name = "solana_libra_execution_proto"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = "0.4.4"
proptest = "0.9.2"
proptest-derive = "0.1.0"
protobuf = "2.7"

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext" }
proptest_helpers = { path = "../../common/proptest_helpers", package = "solana_libra_proptest_helpers" }
proto_conv = { path = "../../common/proto_conv", features = ["derive"], package = "solana_libra_proto_conv" }
types = { path = "../../types", package = "solana_libra_types" }

[build-dependencies]
build_helpers = { path = "../../common/build_helpers", package = "solana_libra_build_helpers" }

[dev-dependencies.types]
features = ["testing"]
path = "../../types"
package = "solana_libra_types"
