[package]
name = "solana_libra_nextgen_crypto"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bincode = "1.1.1"
byteorder = "1.3.2"
bytes = "0.4.12"
curve25519-dalek = "1.1.3"
derive_deref = "1.1.0"
ed25519-dalek = { version = "1.0.0-pre.1", features = ["serde"] }
hex = "0.3"
lazy_static = "1.3.0"
pairing = "0.14.2"
proptest = "0.9.1"
proptest-derive = "0.1.0"
rand = "0.6.5"
serde = { version = "1.0.96", features = ["derive"] }
threshold_crypto = "0.3"
tiny-keccak = "1.5.0"
x25519-dalek = "0.5.2"
digest = "0.8.1"
hmac = "0.7.1"
sha3 = "0.8.2"
sha2 = "0.8.0"

failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol5" }
crypto-derive = { path = "../legacy_crypto/src/macros", package = "solana_libra_crypto-derive", version = "0.0.0-sol5" }
proto_conv = { path = "../../common/proto_conv", package = "solana_libra_proto_conv", version = "0.0.0-sol5" }
crypto = { path = "../legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol5" }

[dev-dependencies]
bitvec = "0.10.1"
byteorder = "1.3.2"
ripemd160 = "0.8.0"

[features]
default = []
testing = []
